name: cd
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "koyeb-${{ github.ref_name }}"
      cancel-in-progress: true
    steps:
      - name: Install & Configure Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

      - name: Deploy from Git (Buildpacks)
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: my-spring-app
          service-name: mute-api
          git-builder: buildpack
          # 필요 시 커맨드 오버라이드(Procfile 대신)
          git-run-command: "java -Dserver.port=$PORT -jar target/*.jar"
          # 환경변수/포트/라우팅
          service-env: "SPRING_PROFILES_ACTIVE=prod,DB_URL=@DB_URL,DB_USER=@DB_USER,DB_PASS=@DB_PASS"
          service-ports: "8080:http"
          service-routes: "/:8080"
