name: CD (Deploy to Koyeb)
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "deploy-${{ github.ref_name }}"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Configure Koyeb
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}
      - name: Build and Deploy
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: springboot-app     #처음 배포 시 앱 자동 생성
          service-name: mute-api       #서비스 이름
          git-builder: buildpack       #도커 대신 Buildpacks
          git-root: back-end
          service-ports: "8080:http"
          service-routes: "/:8080"
          service-checks: "8080:http:/"
          service-env: "JAVA_OPTS=-Xms256m -Xmx512m,SPRING_PROFILES_ACTIVE=cloud"
