name: cd

on:
  workflow_run:
    workflows: [ "ci" ]
    types: [ completed ]
  workflow_dispatch: { }

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: |
          curl -sL https://github.com/koyeb/koyeb-cli/releases/download/v1.3.0/koyeb_1.3.0_Linux_x86_64.tar.gz | tar xz
          sudo mv koyeb /usr/local/bin/

      - name: Update existing Koyeb service
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: |
          koyeb service update my-spring-app/mute-api \
            --git github.com/Team-Mute/back-end \
            --git-branch main \
            --git-builder buildpack \
            --type web \
            --instance-type micro \
            --regions tyo \
            --env SPRING_PROFILES_ACTIVE=ci \
            --env BP_JVM_VERSION=17 \
            --env SPRING_DATASOURCE_URL=${{ secrets.NEON_JDBC_URL }} \
            --env SPRING_DATASOURCE_USERNAME=${{ secrets.NEON_DB_USER }} \
            --env SPRING_DATASOURCE_PASSWORD=${{ secrets.NEON_DB_PASS }} \
            --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --env AWS_REGION=${{ secrets.AWS_REGION }} \
            --env AWS_STACK_AUTO=${{ secrets.AWS_STACK_AUTO }} \
            --env AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }} \
            --env JAVA_TOOL_OPTIONS="-Dserver.port=8080 -XX:MaxRAMPercentage=75.0 -Xms128m -Xmx256m" \
            --ports 8080:http \
            --routes /:8080
