name: ci
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle     # ← Gradle 캐시

      - name: Make gradlew executable (Linux)
        run: chmod +x ./gradlew

      - name: Format code (Spotless + EditorConfig)
        run: ./gradlew spotlessApply editorconfigFormat

      - name: Build (tests included)
        run: ./gradlew clean build --no-daemon

      # Checkstyle 리포트 업로드(리뷰에 유용)
      - name: Upload Checkstyle reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-reports
          path: build/reports/checkstyle/*.html

      # editorconfig-checker도 유지하고 싶다면
      - name: editorconfig-check
        uses: editorconfig-checker/action-editorconfig-checker@v2
